version: '3.3'

services:
  # FastAPI Backend
  backend:
    build:
     context: .
     dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env.${ENV:-development}
    environment:
      - ENV=${ENV:-development}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    #   nats:
    #     condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - project_network

  # Redis Cache
  redis:
    image: redis:8.4
    container_name: WhoWillAnswer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - project_network

  postgres:
    image: postgres:18
    container_name: WhoWillAnswer_postgres
    env_file:
      - .env.${ENV:-development}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-root}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME:-wwa_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - /scripts/init_db.sh:/docker-entrypoint-initdb.d/init.sh:ro
      # - /app/infrastructure/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro    
    command: [ "postgres", "-c", "log_statement=none", "-c", "log_min_duration_statement=1000", "-c", "log_connections=on", "-c", "log_disconnections=on" ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-root} -d ${DATABASE_NAME:-wwa_db}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: