"""add roles and password to User model

Revision ID: d517410b88da
Revises: 8be994cd0390
Create Date: 2026-06-27 07:41:45.409810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd517410b88da'
down_revision: Union[str, Sequence[str], None] = '8be994cd0390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('users', sa.Column('roles', sa.JSON(), server_default='["USER"]', nullable=False))
	op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('users', 'password')
	op.drop_column('users', 'roles')
	# ### end Alembic commands ###
